services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    Sylius\Component\Order\Repository\OrderItemRepositoryInterface:
        alias: sylius.repository.order_item

    App\Form\Type\Checkout\SelectShippingAddressExtension:
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Extension\Checkout\SelectShippingType }

    App\EventSubscriber\Checkout\ShippingAddressSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\Twig\ShippingPriceExtension:
        arguments:
            $calculatorRegistry: '@sylius.registry.shipping_calculator'
        tags: [ 'twig.extension' ]


    App\Service\DistanceCalculator: ~
    
    App\Twig\AppExtension:
        tags: ['twig.extension']
        arguments:
            $distanceCalculator: '@App\Service\DistanceCalculator'
            $pickupPointRepository: '@App\Repository\Shipping\PickupPointRepository'
            

    App\Form\Extension\CheckoutShipmentTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType }

    App\Repository\Shipping\PickupPointRepository:
        tags: [ 'doctrine.repository_service' ]
    

    App\EventListener\Checkout\AutoAddressListener:
        tags:
            - { name: kernel.event_listener, event: workflow.sylius_order_checkout.transition.select_shipping, method: onEnterShippingSelection }
            - { name: kernel.event_listener, event: workflow.sylius_order_checkout.transition.skip_shipping, method: onEnterShippingSelection }